name: CI/CD Pipeline for Codely

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: FrontEnd-React/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        cd FrontEnd-React
        npm install

    - name: Lint Code
      run: |
        cd FrontEnd-React
        npm run lint
      continue-on-error: false

    - name: Build Project
      run: |
        cd FrontEnd-React
        npm run build

    - name: Run Tests
      run: |
        cd FrontEnd-React
        npm run test -- --verbose
      continue-on-error: false

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: FrontEnd-React/coverage

    - name: Run Vite Preview (Optional)
      run: |
        cd FrontEnd-React
        npm run preview
