name: CI/CD Pipeline for Meshnettak

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        cd FrontEnd-React
        npm install

    - name: Lint Code
      run: |
        cd FrontEnd-React
        npm run lint

    - name: Build Project
      run: |
        cd FrontEnd-React
        npm run build

    - name: Run Tests
      run: |
        cd FrontEnd-React
        npm run test

    - name: Run Vite Preview (Optional)
      run: |
        cd FrontEnd-React
        npm run preview
